### ISSUE TITLE
Inconsistent structure of tests' CMakeLists.txt files

### ISSUE THREAD

**Issue by pfalcon** [MCU-Driver-HAL/MCU-Driver-HAL#15]
I'm working on converting the `trng` test to the recent cmake conventions of the project, taking `echo` and `us_ticker` tests as examples.

However, I found that these 2 tests have somewhat inconsistent CMakeLists.txt structure/content:
* https://github.com/MCU-Driver-HAL/MCU-Driver-HAL/blob/main/tests/mbed_hal/echo/CMakeLists.txt
* https://github.com/MCU-Driver-HAL/MCU-Driver-HAL/blob/main/tests/mbed_hal/us_ticker/CMakeLists.txt

The differences are:
* `echo` uses `set(TEST_TARGET_LIB sdfx-test-trng)` and then `${TEST_TARGET_LIB}` to refer to the lib, which make it easier to reuse this file as a sample for other tests (change test lib name in only 1 place instead of many).
* `echo` again uses just `SPDX-License-Identifier:`, while `us_ticker` - full/verbose license blurb. One of the reason behind introduction of `SPDX-License-Identifier:` was exactly to avoid long/repetitive license blurbs (especially on short support files like CMakeLists.txt, like here; I'm personally +1 for using more verbose headers for actual source code files).

So, while `us_ticker` seems to be a newer addition, I personally seem to like `echo`'s conventions more, and keen to use it for `trng`. But that's inconsistency, and while small, there's going to be many cases like this, so I decided to submit this ticket to draw attention to this issue.

**Comment by pfalcon** [comment]
cc: @MarceloSalazar, @fkjagodzinski

**Comment by fkjagodzinski** [comment]
Thanks for catching that! :+1: The CMake file for the `echo` test is the one that should be updated. The CMake file for the `us_ticker` is newer and should serve as a reference.

- The use of an additional variable was questioned already https://github.com/MCU-Driver-HAL/MCU-Driver-HAL/pull/6#discussion_r658767398. Currently I tend to agree that having `${TEST_TARGET_LIB}` doesn't add much value.
- About the license header -- I remember we agreed to use the full version; can't find any written reference though. If we consider the short version sufficient for certain types of files in the project, we can note that when updating the guidelines.

**Comment by fkjagodzinski** [comment]
I'll update https://github.com/MCU-Driver-HAL/MCU-Driver-HAL/blob/main/tests/mbed_hal/echo/CMakeLists.txt to be aligned with other tests.

**Comment by pfalcon** [comment]
@fkjagodzinski:

> The CMake file for the us_ticker is newer and should serve as a reference.

Ack, thanks for confirming and for explanations on details, I'll update my trng PR.

> I'll update https://github.com/MCU-Driver-HAL/MCU-Driver-HAL/blob/main/tests/mbed_hal/echo/CMakeLists.txt to be aligned with other tests.

Thanks!

**Comment by fkjagodzinski** [comment]
@pfalcon, thanks again for rising this! Please review a proposed fix --> #21.
