### ISSUE TITLE
README doesn't provide any info on how to get started

### ISSUE THREAD

**Issue by pfalcon-linaro** [MCU-Driver-HAL/MCU-Driver-HAL#8]
User story: as an end user who just have heard about the great MCU-Driver-HAL project, I'd like to see it in action, to build some example app with it. Current README (https://github.com/MCU-Driver-HAL/MCU-Driver-HAL/commit/f84a167231b823805efca66470654a08ad302e76#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5) doesn't help me in any way.

(Of course, I'm not supposed to be able to see "in action" just this repository alone, I should go to a particular vendor/device implementation repository. And the README should explain that to me and guide to a "sample" repository (or list all the currently available implementations). Currently, the README just says "This repository is referenced from Silicon Partners Drivers.", and it's hard to infer all the above from that.)

**Comment by MarceloSalazar** [comment]
Fixed in https://github.com/MCU-Driver-HAL/MCU-Driver-HAL/pull/16
