### ISSUE TITLE
PR merging/linear history requirements

### ISSUE THREAD

**Issue by pfalcon-linaro** [MCU-Driver-HAL/MCU-Driver-HAL#9]
Some time ago, there was discussion of how change merging would happen and project history would be maintained. Specifically, whether we want to avoid introducing merge commits, and instead maintain linear project history (many projects nowadays choose to maintain linear project history, as it simplifies change browsing, project history querying, bisecting, etc).

Sadly, I cannot find references to that (discussion about the project is spread around, perhaps it was in a weekly meeting at all), but IIRC, the consensus was on following linear history for MCU-Driver-HAL too. But as of now, we already have 2 merge commits in the repository: https://github.com/MCU-Driver-HAL/MCU-Driver-HAL/commit/f5d96b068b07f7b98cb833726c103aa2f7715ab8 , https://github.com/MCU-Driver-HAL/MCU-Driver-HAL/commit/ee27993b24db117abd69c6fe543383242e6fe26c .

Perhaps, we should revisit and make related changed in the project settings. Note that the changes would be simple: go to https://github.com/MCU-Driver-HAL/MCU-Driver-HAL/settings , scroll to "Merge button" section, and uncheck "Allow merge commits" option. (Maybe also uncheck "Allow squash merging" option to preclude errors with its usage; developers can the squash changes in their git client/be requested to do that in review. Thus, only "Allow rebase merging" would be checked, which is exactly the option required to maintain linear project history.)

**Comment by pfalcon-linaro** [comment]
cc @MarceloSalazar, @galak, @evedon.

**Comment by evedon** [comment]
Thanks for raising the issue. This topic was discussed among some project members but no decision has been made yet. 
We are planning to make a proposal on PR Processes, including PR merging/linear history requirements next week.

**Comment by 0xc0170** [comment]
Disallowing all but Rebase and merge sounds like a good option.

Additionally, no merge commits within contributions - always rebase (not certain how to handle subtree merge - I have an experience when one project uses subtree merge - https://github.com/ARMmbed/mbed-os/pull/14833 - is this something to consider it might happen ?).

**Comment by 0xc0170** [comment]
#26 was resolved, the main branch has only rebase and merge enabled.  I'll close this as fixed.
